#!/usr/bin/env node
const DB = require('./chefs-tools') 

/* Joes custom migration script :)
	create: ./back-of-house/migrations up
	drop: ./back-of-house/migrations down
	on heroku: heroku run ./back-of-house/migrations (up/down)
*/

const args = process.argv.slice(2)

if(!args[0]) return console.log('But what u wanna DO tho?')

switch(args[0].toLowerCase()) {
  case 'up': return make()
  case 'down': return destroy()
  default: return console.log('nah')
}

// createTable
function make() {
  return DB.tableMaker({
    table: 'gizz2017',
    columns: [
      {name: 'album_name', type: 'char(255)'},
      {name: 'fav_track', type: 'char(255)'},
      {name: 'eee_yup', type: 'bool'},
    ]
  })
  .then(() => console.log('hi'))
}

// dropTable
function destroy() {
  return DB.tableBreaker('gizz2017')
  .then(() => console.log('hi'))
}